docker

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -44,43 +44,53 @@ jobs:
       # リポジトリをチェックアウト
       - name: Checkout
         uses: actions/checkout@v2
+      
+      - name: docker Build
+        run: docker-compose build
+      - name: Docker Compose Up
+        run: docker-compose up -d
+      - name: Pipenv Install
+        run: docker-compose exec -T app pipenv install
+      - name: Pipenv Run Pytest
+        run: docker-compose exec -T app pipenv run pytest
 
-      # Pythonの環境をセットアップ
-      - name: Set up Python 3.7
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
 
-      # pytestをインストール
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pytest
+      # # Pythonの環境をセットアップ
+      # - name: Set up Python 3.7
+      #   uses: actions/setup-python@v2
+      #   with:
+      #     python-version: 3.7
 
-      # pytest -> JUnit xml形式で結果を出力
-      - name: PyTest
-        run: |
-          python -m pytest test --junit-xml results/pytest.xml
-        continue-on-error: true
+      # # pytestをインストール
+      # - name: Install dependencies
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     pip install pytest
 
-      # テスト結果の表示
-      - name: Upload Unit Test Results
-        if: ${{ always() }}
-        uses: actions/upload-artifact@v2
-        with:
-          name: Unit Test Results (Python 3.7)
-          path: results/*.xml
+      # # pytest -> JUnit xml形式で結果を出力
+      # - name: PyTest
+      #   run: |
+      #     python -m pytest --junit-xml results/pytest.xml
+      #   continue-on-error: true
 
-      - name: Download Artifacts
-        if: success() || failure()
-        uses: actions/download-artifact@v2
-        with:
-          path: artifacts
+      # # テスト結果の表示
+      # - name: Upload Unit Test Results
+      #   if: ${{ always() }}
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: Unit Test Results (Python 3.7)
+      #     path: results/*.xml
 
-      - name: Publish Unit Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v1
-        with:
-          files: artifacts/**/*.xml
+      # - name: Download Artifacts
+      #   if: success() || failure()
+      #   uses: actions/download-artifact@v2
+      #   with:
+      #     path: artifacts
+
+      # - name: Publish Unit Test Results
+      #   uses: EnricoMi/publish-unit-test-result-action@v1
+      #   with:
+      #     files: artifacts/**/*.xml
 
 
 # #-- End of yaml
